// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.21.12
// source: signalcodex/messages/error.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorSalience int32

const (
	ErrorSalience_LOW_ERR_SALIENCE      ErrorSalience = 0
	ErrorSalience_MED_ERR_SALIENCE      ErrorSalience = 1
	ErrorSalience_HIGH_ERR_SALIENCE     ErrorSalience = 2
	ErrorSalience_CRITICAL_ERR_SALIENCE ErrorSalience = 3
	ErrorSalience_FATAL_ERR_SALIENCE    ErrorSalience = 4
)

// Enum value maps for ErrorSalience.
var (
	ErrorSalience_name = map[int32]string{
		0: "LOW_ERR_SALIENCE",
		1: "MED_ERR_SALIENCE",
		2: "HIGH_ERR_SALIENCE",
		3: "CRITICAL_ERR_SALIENCE",
		4: "FATAL_ERR_SALIENCE",
	}
	ErrorSalience_value = map[string]int32{
		"LOW_ERR_SALIENCE":      0,
		"MED_ERR_SALIENCE":      1,
		"HIGH_ERR_SALIENCE":     2,
		"CRITICAL_ERR_SALIENCE": 3,
		"FATAL_ERR_SALIENCE":    4,
	}
)

func (x ErrorSalience) Enum() *ErrorSalience {
	p := new(ErrorSalience)
	*p = x
	return p
}

func (x ErrorSalience) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorSalience) Descriptor() protoreflect.EnumDescriptor {
	return file_signalcodex_messages_error_proto_enumTypes[0].Descriptor()
}

func (ErrorSalience) Type() protoreflect.EnumType {
	return &file_signalcodex_messages_error_proto_enumTypes[0]
}

func (x ErrorSalience) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorSalience.Descriptor instead.
func (ErrorSalience) EnumDescriptor() ([]byte, []int) {
	return file_signalcodex_messages_error_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Salience      ErrorSalience          `protobuf:"varint,2,opt,name=Salience,proto3,enum=ErrorSalience" json:"Salience,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_signalcodex_messages_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_signalcodex_messages_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_signalcodex_messages_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetSalience() ErrorSalience {
	if x != nil {
		return x.Salience
	}
	return ErrorSalience_LOW_ERR_SALIENCE
}

func (x *Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Error) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_signalcodex_messages_error_proto protoreflect.FileDescriptor

var file_signalcodex_messages_error_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x63, 0x6f, 0x64, 0x65, 0x78, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x01, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x2a, 0x0a, 0x08, 0x53, 0x61, 0x6c, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x61, 0x6c, 0x69, 0x65,
	0x6e, 0x63, 0x65, 0x52, 0x08, 0x53, 0x61, 0x6c, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x38, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2a, 0x85, 0x01, 0x0a, 0x0d, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x53, 0x61, 0x6c, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x4c,
	0x4f, 0x57, 0x5f, 0x45, 0x52, 0x52, 0x5f, 0x53, 0x41, 0x4c, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x45, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x5f, 0x53, 0x41, 0x4c,
	0x49, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x48, 0x49, 0x47, 0x48, 0x5f,
	0x45, 0x52, 0x52, 0x5f, 0x53, 0x41, 0x4c, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x02, 0x12, 0x19,
	0x0a, 0x15, 0x43, 0x52, 0x49, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x5f, 0x53,
	0x41, 0x4c, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x46, 0x41, 0x54,
	0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x5f, 0x53, 0x41, 0x4c, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x10,
	0x04, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_signalcodex_messages_error_proto_rawDescOnce sync.Once
	file_signalcodex_messages_error_proto_rawDescData = file_signalcodex_messages_error_proto_rawDesc
)

func file_signalcodex_messages_error_proto_rawDescGZIP() []byte {
	file_signalcodex_messages_error_proto_rawDescOnce.Do(func() {
		file_signalcodex_messages_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_signalcodex_messages_error_proto_rawDescData)
	})
	return file_signalcodex_messages_error_proto_rawDescData
}

var file_signalcodex_messages_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_signalcodex_messages_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_signalcodex_messages_error_proto_goTypes = []any{
	(ErrorSalience)(0),            // 0: ErrorSalience
	(*Error)(nil),                 // 1: Error
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_signalcodex_messages_error_proto_depIdxs = []int32{
	0, // 0: Error.Salience:type_name -> ErrorSalience
	2, // 1: Error.Timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_signalcodex_messages_error_proto_init() }
func file_signalcodex_messages_error_proto_init() {
	if File_signalcodex_messages_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_signalcodex_messages_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_signalcodex_messages_error_proto_goTypes,
		DependencyIndexes: file_signalcodex_messages_error_proto_depIdxs,
		EnumInfos:         file_signalcodex_messages_error_proto_enumTypes,
		MessageInfos:      file_signalcodex_messages_error_proto_msgTypes,
	}.Build()
	File_signalcodex_messages_error_proto = out.File
	file_signalcodex_messages_error_proto_rawDesc = nil
	file_signalcodex_messages_error_proto_goTypes = nil
	file_signalcodex_messages_error_proto_depIdxs = nil
}
