// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.21.12
// source: messages/system_alert.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemAlertSalience int32

const (
	SystemAlertSalience_LOW_ALERT_SALIENCE      SystemAlertSalience = 0
	SystemAlertSalience_MED_ALERT_SALIENCE      SystemAlertSalience = 1
	SystemAlertSalience_HIGH_ALERT_SALIENCE     SystemAlertSalience = 2
	SystemAlertSalience_CRITICAL_ALERT_SALIENCE SystemAlertSalience = 3
	SystemAlertSalience_FATAL_ALERT_SALIENCE    SystemAlertSalience = 4
)

// Enum value maps for SystemAlertSalience.
var (
	SystemAlertSalience_name = map[int32]string{
		0: "LOW_ALERT_SALIENCE",
		1: "MED_ALERT_SALIENCE",
		2: "HIGH_ALERT_SALIENCE",
		3: "CRITICAL_ALERT_SALIENCE",
		4: "FATAL_ALERT_SALIENCE",
	}
	SystemAlertSalience_value = map[string]int32{
		"LOW_ALERT_SALIENCE":      0,
		"MED_ALERT_SALIENCE":      1,
		"HIGH_ALERT_SALIENCE":     2,
		"CRITICAL_ALERT_SALIENCE": 3,
		"FATAL_ALERT_SALIENCE":    4,
	}
)

func (x SystemAlertSalience) Enum() *SystemAlertSalience {
	p := new(SystemAlertSalience)
	*p = x
	return p
}

func (x SystemAlertSalience) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemAlertSalience) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_system_alert_proto_enumTypes[0].Descriptor()
}

func (SystemAlertSalience) Type() protoreflect.EnumType {
	return &file_messages_system_alert_proto_enumTypes[0]
}

func (x SystemAlertSalience) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemAlertSalience.Descriptor instead.
func (SystemAlertSalience) EnumDescriptor() ([]byte, []int) {
	return file_messages_system_alert_proto_rawDescGZIP(), []int{0}
}

type SystemAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Salience      SystemAlertSalience    `protobuf:"varint,2,opt,name=Salience,proto3,enum=SystemAlertSalience" json:"Salience,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemAlert) Reset() {
	*x = SystemAlert{}
	mi := &file_messages_system_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemAlert) ProtoMessage() {}

func (x *SystemAlert) ProtoReflect() protoreflect.Message {
	mi := &file_messages_system_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemAlert.ProtoReflect.Descriptor instead.
func (*SystemAlert) Descriptor() ([]byte, []int) {
	return file_messages_system_alert_proto_rawDescGZIP(), []int{0}
}

func (x *SystemAlert) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SystemAlert) GetSalience() SystemAlertSalience {
	if x != nil {
		return x.Salience
	}
	return SystemAlertSalience_LOW_ALERT_SALIENCE
}

func (x *SystemAlert) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SystemAlert) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_messages_system_alert_proto protoreflect.FileDescriptor

var file_messages_system_alert_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x5f, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf,
	0x01, 0x0a, 0x0b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x53, 0x61, 0x6c, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x53, 0x61, 0x6c, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x08, 0x53, 0x61, 0x6c, 0x69,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2a, 0x95, 0x01, 0x0a, 0x13, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x41, 0x6c, 0x65, 0x72, 0x74,
	0x53, 0x61, 0x6c, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x4c, 0x4f, 0x57, 0x5f,
	0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f, 0x53, 0x41, 0x4c, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x00,
	0x12, 0x16, 0x0a, 0x12, 0x4d, 0x45, 0x44, 0x5f, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f, 0x53, 0x41,
	0x4c, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x48, 0x49, 0x47, 0x48,
	0x5f, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f, 0x53, 0x41, 0x4c, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x10,
	0x02, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x52, 0x49, 0x54, 0x49, 0x43, 0x41, 0x4c, 0x5f, 0x41, 0x4c,
	0x45, 0x52, 0x54, 0x5f, 0x53, 0x41, 0x4c, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x03, 0x12, 0x18,
	0x0a, 0x14, 0x46, 0x41, 0x54, 0x41, 0x4c, 0x5f, 0x41, 0x4c, 0x45, 0x52, 0x54, 0x5f, 0x53, 0x41,
	0x4c, 0x49, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x04, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_system_alert_proto_rawDescOnce sync.Once
	file_messages_system_alert_proto_rawDescData = file_messages_system_alert_proto_rawDesc
)

func file_messages_system_alert_proto_rawDescGZIP() []byte {
	file_messages_system_alert_proto_rawDescOnce.Do(func() {
		file_messages_system_alert_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_system_alert_proto_rawDescData)
	})
	return file_messages_system_alert_proto_rawDescData
}

var file_messages_system_alert_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_system_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_messages_system_alert_proto_goTypes = []any{
	(SystemAlertSalience)(0),      // 0: SystemAlertSalience
	(*SystemAlert)(nil),           // 1: SystemAlert
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_messages_system_alert_proto_depIdxs = []int32{
	0, // 0: SystemAlert.Salience:type_name -> SystemAlertSalience
	2, // 1: SystemAlert.Timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_messages_system_alert_proto_init() }
func file_messages_system_alert_proto_init() {
	if File_messages_system_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_system_alert_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_system_alert_proto_goTypes,
		DependencyIndexes: file_messages_system_alert_proto_depIdxs,
		EnumInfos:         file_messages_system_alert_proto_enumTypes,
		MessageInfos:      file_messages_system_alert_proto_msgTypes,
	}.Build()
	File_messages_system_alert_proto = out.File
	file_messages_system_alert_proto_rawDesc = nil
	file_messages_system_alert_proto_goTypes = nil
	file_messages_system_alert_proto_depIdxs = nil
}
